config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/', controller: "businesses", action: "index"

  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  delete 'login', to: 'sessions#destroy'

  # resources :sessions

  resources :users
  
  resources :businesses

  resources :business_comments

  resources :business_user_relationships

  resources :user_user_relationships

  resources :user_check_ins

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true
  
end

app/models/business.rb
class Business < ApplicationRecord

  geocoded_by :address
  after_validation :geocode

  has_many :business_comments
  has_many :users, through: :business_comments
  has_many :ratings
  has_many :users, through: :ratings
  has_many :business_user_relationships
  has_many :users, through: :business_user_relationships
  has_many :user_check_ins
  has_many :users, through: :user_check_ins

  def average
    average = 0
    self.ratings.each do |rating|
      average = average + rating.rating
    end

    if self.ratings.length == 0
      return 0
    else
      average/self.ratings.length
    end
  end
  
end

app/models/business_comment.rb
class BusinessComment < ApplicationRecord

  validates :body, presence: true,
    length: { maximum: 100 , message: "over 100 characters"},
    format: { with: /\A[a-zA-Z0-9 !.,'?]+\z/i, message: "special characters are not allowed" }

  belongs_to :business
  belongs_to :user
  
end

app/models/business_user_relationship.rb
class BusinessUserRelationship < ApplicationRecord

  belongs_to :business
  belongs_to :user
  
end

app/models/rating.rb
class Rating < ApplicationRecord
    belongs_to :business
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
   
  has_secure_password

  validates :username, presence: true,
    length: { minimum: 2, maximum: 15 , message: "must be between 2-15 characters"}, 
    format: { with: /\A[a-zA-Z0-9_]+\z/i, message: "can only consist of letters, numbers and underscores" },
    uniqueness: true
  validates :firstname, presence: true,
    length: { minmum: 2, maximum: 15, message: "must be between 2-15 characters"},
    format: { with: /\A[a-zA-Z]+\z/i, message: "can only consist of letters"}
  validates :password, presence: true,
    length: { minimum: 6, maximum: 15, message: "must be between 6-15 characters"}

  has_many :business_comments
  has_many :businesses, through: :business_comments
  has_many :ratings
  has_many :businesses, through: :ratings
  has_many :business_user_relationships
  has_many :businesses, through: :business_user_relationships
  has_many :user_user_relationships
  has_many :users, through: :user_user_relationships
  has_many :user_check_ins
  has_many :businesses, through: :user_check_ins

  has_one_attached :avatar
  # has_may_attached

end

app/models/user_check_in.rb
class UserCheckIn < ApplicationRecord

  belongs_to :business
  belongs_to :user

end

app/models/user_user_relationship.rb
class UserUserRelationship < ApplicationRecord

  belongs_to :user

  def friend?(users, current_user)
    if (self.user_id == current_user.id) && (self.relationship == true)
      users.where(id: self.friend_user_id).first.firstname
    elsif (self.friend_user_id == current_user.id) && (self.relationship == true)
      users.where(id: self.user_id).first.firstname
    end
  end

  def friend_requests?(current_user)
    if (self.friend_user_id == current_user.id) && !(self.relationship == true)
      true
    end
  end

  # def friend_or_request?(user, current_user)
  #   if !(self == nil)
  #     if !(self.user_id == user.id && self.friend_user_id == current_user.id && self.relationship = true)
  #       if !(self.user_id == current_user.id && self.friend_user_id == user.id && self.relationship = true)
  #         if !(self.user_id == user.id && self.friend_user_id == current_user.id && self.relationship = false)
  #           if !(self.user_id == current_user.id && self.friend_user_id == user.id && self.relationship = false)
  #             true
  #           end
  #         end
  #       end
  #     end
  #   end
  # end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def current_user
    User.find_by(id: session[:user_id])
  end
  
  helper_method :current_user

  def logged_in?
    !current_user.nil?
  end
  helper_method :logged_in? 
   
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController

  def index
    @businesses = Business.all
  end

  def show
    @business = Business.where(id: params[:id]).first
    @business_comments = @business.business_comments
    @ratings = Rating.all
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    render plain: "Final Project"
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
    
      redirect_to '/'
    else

      redirect_to '/login'
    end
  end

  def destroy
    reset_session

    redirect_to '/'
  end
  
end

app/controllers/user_check_ins_controller.rb
class UserCheckInsController < ApplicationController

  def index
    @user_check_ins = UserCheckIn.all
  end
  
  def new
    @user_check_in = UserCheckIn.new 
  end
  
  def create
    @user_check_in = UserCheckIn.create(params.require(:user_check_in).permit(:checked_in, :business_id, :user_id))
  
    redirect_to request.referrer
  end
  
  def destroy
    @user_check_in = UserCheckIn.find(params[:id])
    @user_check_in.destroy
  
    redirect_to request.referrer
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
  def index
    @user_relationships = UserUserRelationship.all
    @user_check_ins = UserCheckIn.all

    @businesses = Business.all
    @users = User.all
  end

  def show
  end
  
  def new
    @user = User.new
  end

  def create
    # @user = User.create(params.require(:user).permit(:firstname, :username, :password))
    @user = User.new(params.require(:user).permit(:avatar, :firstname, :username, :password))
    if @user.valid?
      @user.save
      session[:user_id] = @user.id

      redirect_to '/users'
    else
      flash.now[:messages] = @user.errors.full_messages[0]

      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/business_comments_helper.rb
module BusinessCommentsHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_check_ins_helper.rb
module UserCheckInsHelper
end

app/helpers/user_user_relationships_helper.rb
module UserUserRelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/businesses/clipboard.html.erb
        <%# business.ratings.each do |rating|%>
            <%# <div><%# rating.rating %></div> %>
        <%# end %>
        <%# if business.ratings[0] %>
            <%# <div class="bc_rating">Rating: <%#= business.ratings[0].rating#</div> %> %>
        <%# else %>
            <%# <div class="bc_rating">Be the first to rate!</div> %>
        <%# end %>
        <%# if business.business_comments[0] %>
            <%# <div>Comment: "= business.business_comments[0].body"</div> %>
        <%# else%>
            <%# <div>No User Commnets Yet</div> %>
        <%# end %>
        <% @business_comments.each do |comment | %>
    <div><%= comment.body %></div>
<% end %>
<div>Comment: "<%= @business.business_comments[0].body %>"</div>

                <% if average(business, @ratings) == 5 %>
            <div>Be the first to rate this business</div>
        <% end %>
            <% if @ratings.length == 0 %>
                <div>Be the first to rate this business</div>
        <% end %>
        <%= average(business, @ratings) %>

        <%= button_to "Logout" destroy_session_path, method: :destroy %>
Why does this not work? Ahhhhhh not in resources
<div><%= link_to "Login2", new_session_path %></div>
<div><%= button_to "login", "/login", method: :get  %></div>
<div><%= button_to "logout", "/login", method: :destroy %></div>
<div><%= button_to "lougout2", "/login", method: :destroy %></div>





        <% if average(business, @ratings) > 0 %>
            <div><%= average(business, @ratings)%> </div>
        <% else %>
            <div>Be the first to rate this business</div>
        <% end %>



        size=640x400&key=AIzaSyAuDaaz9Df8EH6dulqrvhGzxSap3DErSOY

        <div><%= image_tag google_map(center: @business.address) %> </div>
<img src="<%= google_map(center: [@business.latitude, @business.longitude].join(',')) %>"/>

<div><%= image_tag google_map(center: @business.address) %> </div>
<img src="<%= google_map(center: [@business.latitude, @business.longitude].join(',')) %>"/>

<div><%= @business.address %></div>
<div><%= @business.latitude %></div>
<div><%= @business.longitude %></div>

<% provide :head_tags do %>
    <script>
    document.addEventListener("DOMContentLoaded", function(){
        initMap(<%=@business.latitude%>, <%=@business.longitude%>)
    });
    </script>
<% end %>

    <%# <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAuDaaz9Df8EH6dulqrvhGzxSap3DErSOY&callback=initMap" ></script> %>
        <script
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAuDaaz9Df8EH6dulqrvhGzxSap3DErSOY&callback=initMap&libraries=&v=weekly"
      async
    ></script>



#map {
    height: 100%;
  }
  
  /* Optional: Makes the sample page fill the window. */
  html,
  body {
    height: 100%;
    margin: 0;
    padding: 0;
  }
      <%= yield(:head_tags) %>


      added to config > initializers > assets

      # Added to use google map 
Rails.application.config.assets.precompile += %w(application.js)

static map code
    <%# <div><%#= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@business.latitude},#{@business.longitude}&markers=#{@business.latitude},#{@business.longitude}&zoom=17&size=400x400&key=AIzaSyAuDaaz9Df8EH6dulqrvhGzxSap3DErSOY",
              class: 'img-fluid img-rounded', alt: "#{@business.name} on the map"%></div> %>


              <p><%= @business.name %></p>
<p><%= @business_comments.where(user_id: current_user.id, business_id: @business.id).first.body %></p>
<p><%= current_user.firstname %></p>
<p><%= current_user.id %></p>

<% if @business_comments.where(user_id: current_user.id, business_id: @business.id) == nil%>
    <p>true</p>
    <%end%>

<%= current_user.id %>
<%= @business.id%>
<%#= @business_comments.where(user_id: 1, business_id: 6).first.body %>

       <%# <h1>Hi <%#= current_user.firstname %>: a comment and rating form will go here once I figure out how to do it</h1>
        <h1>Log in check is working though, how freaking cool is that???</h1> %>

          <div>USER<%= user_relationship.id%></div>
    <%= user_relationship.user_id %>
    <%= user_relationship.friend_user_id %>
    <%= user_relationship.relationship %> 

    <p>friend first name <%= current_user.firstname %></p>
<p>friend id <%= current_user.id %></p>

@user_relationships.where(user_id: user.id, friend_user_id: current_user.id, relationship: true).first.user.firstname

    # def average(business)
    #     average = 0
    #     business.ratings.each do |rating|
    #         average = average + rating.rating
    #     end
    #     if business.ratings.length == 0
    #         return 0
    #     else
    #         average/business.ratings.length
    #     end
    #     # puts ratings.length
    #     # puts average / ratings.length
    # end
    # helper_method :average

  
    # def google_map(center)
    #     "https://maps.googleapis.com/maps/api/staticmap?center=#{center}&size=300x300&zoom=17size=640x400&key=AIzaSyAuDaaz9Df8EH6dulqrvhGzxSap3DErSOY"
    # end
    # helper_method :google_map

<%= link_to "home", :businesses, class: "show-home-link" %>

https://medium.com/@traciemasek/validations-and-flash-in-rails-the-basics-1f2af5b2e61c

            # flash.now[:messages] = @user.errors.full_messages

<% if flash[:messages] %>
    <% flash[:messages].each do |message| %>
        <h2 class="register-flash"><%= flash[:messages] %></h2>
    <%end%>
<%end%>

<div><%= link_to "home", businesses_path %></div>

# had to get rid of .now on flash to get this to work because I couldn't use render :new cause it is in a different controller
            flash[:messages] = @business_comment.errors.full_messages[0]

            https://stackoverflow.com/questions/9815673/how-to-display-a-flash-message-immediately-from-within-a-controller-method

check if friend
                <% if (user_relationship.user_id == current_user.id) && (user_relationship.relationship == true) %>
        <div><%= @users.where(id: user_relationship.friend_user_id).first.firstname %></div>
    <% elsif(user_relationship.friend_user_id == current_user.id) && (user_relationship.relationship == true) %>
        <div><%= @users.where(id: user_relationship.user_id).first.firstname %></div>
    <%end%>

check for friend request
<% if (user_relationship.friend_user_id == current_user.id) && !(user_relationship.relationship == true) %>

<h2>Friend Requests</h2>
<% @user_relationships.each do |user_relationship|%>
    <% if (user_relationship.friend_user_id == current_user.id) && !(user_relationship.relationship == true) %>
        <p>You have a friend request from <%= @users.where(id: user_relationship.user_id).first.firstname %></p>
        <%= form_for :user_user_relationship, url:"/user_user_relationships/#{user_relationship.id}", method: :put do |f| %>
            <%= f.hidden_field :relationship, value: true %>
            <%= f.submit %>
        <%end%>
    <%end%>
<% end %>   


<% @users.each do |user| %>

    <% if (user.id != current_user.id) %>
        <% if @user_relationships.where(user_id: user.id, friend_user_id: current_user.id, relationship: true).first == nil %>
            <% if @user_relationships.where(user_id: current_user.id, friend_user_id: user.id, relationship: true).first == nil%>
                <% if @user_relationships.where(user_id: user.id, friend_user_id: current_user.id, relationship: false).first == nil %>
                    <% if @user_relationships.where(user_id: current_user.id, friend_user_id: user.id, relationship: false).first == nil%>



                    !(business.user_check_ins.first == nil)  && 


                        <% if !(business.user_check_ins.first == nil)  && 
          (!(business.user_check_ins.first.user.user_user_relationships.where(id: current_user.id, relationship: true).first == nil)  || 
          !(business.user_check_ins.first.user.user_user_relationships.where(friend_user_id: current_user.id, relationship: true).first == nil))  %>
        <%= business.user_check_ins.first.user.firstname %>
        <%end%>

        Article about uploading pictures you used

        https://medium.com/@anaharris/how-to-add-image-upload-functionality-to-your-rails-app-9f7fc3f3d042




        <% current_user.user_user_relationships.each do |user_relationship| %>
            <% if user_relationship.relationship == true %>

                        <div  style="display: flex">
                            <div><%= user_relationship.user.firstname %>  </div>
                            <%= form_for :user_user_relationship, url:"/user_user_relationships" do |f| %>
                                <%= f.hidden_field :user_id, value: current_user.id %>
                                <%= f.hidden_field :friend_user_id, value: user_relationship.user.id %>
                                <div style="margin-left: 20px; margin-bottom: 8px;"><%= f.submit "Send friend request", class: "page-top-buttons" %></div>
                            <%end%>
                        </div>
  
            <%end%>  
        <%end%>


          <div class="future-navbar-items">
    <div class="greeting">
        <div><%= button_to "Home", '/businesses', method: :get, class: "page-top-buttons" %></div>

    <% if logged_in? %>
        <div class="page-top-buttons">make a navbar partial</div>
        <div class="greet">Hi <%= current_user.firstname %>!</div>
        <div><%= button_to "#{current_user.firstname}'s Dashboard", '/users', method: :get, class: "page-top-buttons" %></div>
        <div><%= button_to "logout", "/login", method: :delete, class: "page-top-buttons" %></div>
        <div><%= button_to "#{current_user.firstname}'s Profile", "/users/#{current_user.id}", method: :get, class: "page-top-buttons" %></div>
    <% else %>
        <div><%= button_to "register", "/users/new", method: :get, class: "page-top-buttons" %></div>
        <div><%= button_to "login", "/login", method: :get, class: "page-top-buttons"  %></div>
    <% end %>
  </div>
</div>



<%= button_to "login", "/login", method: :get, class: "top-buttons"%>


        <%# <div><%= button_to "Home", '/businesses', method: :get, class: "page-top-buttons" %></div> %>


                    <div class="bc_address"><%= business.city %>, <%= business.state_abbrev %> <%= business.zip_code %></div>
            <div class="bc_type"><%= business.business_type %></div>

app/views/businesses/index.html.erb
<div class="header-background">

<div class="header-buttons" style="text-align: right; margin-top: 100px; margin-right: 100px">
  <% if logged_in? %>
    <div style="float-right;"><%= button_to "Dashboard", '/users', method: :get, class: "top-buttons" %></div>
    <div style="float-right"><%= button_to "logout", "/login", method: :delete, class: "top-buttons" %></div>
  <% else %>
    <div><%= button_to "register", "/users/new", method: :get, class: "top-buttons" %></div>
    <div><%= button_to "login", "/login", method: :get, class: "top-buttons"  %></div>
  <% end %>
  </div>
  <div style="font-size:70px; padding-top: 150px; padding-left: 100px; font-weight: bold">Dog Friendly</div>
  <div style="font-size:30px; padding-top: 50px; padding-left: 100px;">Your Guide to Dog Friendly Businesses in St. Pete</div>
</div>

<div class="business-card-container" style="max-width: 1700px; margin-left: auto; margin-right: auto; margin-top: 40px">
  <% @businesses.each do |business | %>
    <div class="business_card">    
      <img class="bc_img" src="<%= business.img_url %>"/>
      <div class="bc_name" style="font-size: 20px; margin-bottom: 0px;"><%= business.name %></div>
                        <%# <p class="rating">Rating:</p>  %>
      <div style="display: flex; justify-content: center; margin-bottom: 8px;">
        <% if business.average  %>               
          <div class="paws" style="text-align: center">
            <% business.average.times do |i| %>
              <img class="paw" src="<%= asset_path('paw.png') %>"/>
            <% end %>
            <% (5 - business.average).times do |i| %>
              <img class="paw" src="<%= asset_path('graypaw.png') %>"/>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="bc_phone" style="margin-bottom: 5px;"><%= business.phone_number %></div>       
      <div class="bc_address"><%= business.address_number %> <%= business.street_name %></div>
      <div style="display: flex; justify-content: center; margin-top: 50px;">
        <div><%= link_to "More", business, class: "top-buttons", style: "text-decoration: none; font-size: 15px; padding: 5px;" %></div>
      </div>
      <span style="font-weight: bold;"> <%= business.average %> Paws </span>
    </div>
    </br>
  <% end %>
</div>

app/views/businesses/show.html.erb
<script>
    let map;

    function initMap() {
        const myLatLing = { lat: <%= @business.latitude %>, lng: <%= @business.longitude %> }
        const map = new google.maps.Map(document.getElementById("map"), {
          center: myLatLing,
          zoom: 17,
        });
        const image = {
            url: "https://image.flaticon.com/icons/png/512/21/21645.png",
            scaledSize: new google.maps.Size(50, 50),
            origin: new google.maps.Point(0,0),
            anchor: new google.maps.Point(0,0)
        };
        const bikeLayer = new google.maps.BicyclingLayer();
        bikeLayer.setMap(map);
        new google.maps.Marker({
            position: myLatLing,
            map,
            icon: image,
            animation: google.maps.Animation.DROP,
            title: "<%= @business.name %>"
        })
    }
</script>
<div class="future-navbar-items">
  <div class="greeting" style="width: 100%; background: gray; padding-bottom: 10px; padding-top: 10px; position:fixed;">
    <div style="margin-left: 10px; margin-top: auto; margin-bottom: auto; font-size: 30px; margin-right: 40px; color: white;">
      <span style="border: 3px solid white; border-radius: 100%; padding: 5px; background-color: rgba(0, 0, 0, 0.5);">DF</span> 
        St. Pete
    </div>
    <div style="text-align: left;"><%= button_to "Home", '/businesses', method: :get, class: "top-buttons", style: "margin:0px; padding-top: 2px; padding-bottom: 2px;" %></div>
      <% if logged_in? %>
        <div><%= button_to "Profile", "/users/#{current_user.id}", method: :get, class: "top-buttons", style: "margin:0px; padding-top: 2px; padding-bottom: 2px;"%></div>
        <div><%= button_to "Dashboard", '/users', method: :get, class: "top-buttons", style: "margin:0px; padding-top: 2px; padding-bottom: 2px;" %></div>
      <div>
        <% if logged_in?  %>
          <% if @business.business_user_relationships.where(user_id: current_user.id, business_id: @business.id).first == nil %>
            <%= form_for :business_user_relationship, url:"/business_user_relationships" do |f| %>
              <%= f.hidden_field :relationship, value: true %>
              <%= f.hidden_field :business_id, value: @business.id %>
              <%= f.hidden_field :user_id, value: current_user.id %>
              <%= f.submit  "Save Business", class: "top-buttons", style: "margin:0px; padding-top: 2px; padding-bottom: 2px;" %>
            <%end%>
          <%end%>
        <% end%>
      </div>
      <div>
        <% if logged_in?  %>
          <% if @business.user_check_ins.where(user_id: current_user.id, business_id: @business.id).first == nil %>
            <%= form_for :user_check_in, url:"/user_check_ins" do |f| %>
              <%= f.hidden_field :checked_in, value: true %>
              <%= f.hidden_field :business_id, value: @business.id %>
              <%= f.hidden_field :user_id, value: current_user.id %>
              <%= f.submit "Check In", class: "top-buttons", style: "margin:0px; padding-top: 2px; padding-bottom: 2px;" %>
            <%end%>
          <%end%>
        <% end%>
      </div>
      <div><%= button_to "Logout", "/login", method: :delete, class: "top-buttons", style: "margin:0px; padding-top: 2px; padding-bottom: 2px;" %></div>
    </div>
  <% else %>
 <% end %>  
</div >

<div>
  <div class="all-body" style="margin-left: 20em;">
    <div style="margin-top: 100px; font-size: 50px;"><%= @business.name %></div>
    <div class="show-business-info">
      <img class="show-img" style="border-radius: 5px;" src="<%= @business.img_url %>" />
      <div class="stuff">
        <div style="display: flex; justify-content: left; margin-bottom: 8px;">
          <% if @business.average  %>               
            <div class="paws" style="text-align: center">
              <% @business.average.times do |i| %>
                <img class="paw" src="<%= asset_path('paw.png') %>"/>
              <% end %>
              <% (5 - @business.average).times do |i| %>
                <img class="paw" src="<%= asset_path('graypaw.png') %>"/>
              <% end %>  
            </div>
          <% end %>
        </div>
        <div class="show" style="font-size: 23px; padding-top: 5px; padding-bottom: 5px; color: black;">
          <div class="show-web-address"><%= link_to "#{@business.website}", "https://www.#{@business.website}", :target => "blank", style: "text-decoration: none; color: gray; margin-bottom: 8px;" %></div>
          <div class="show-phone"><%= @business.phone_number %></div>
          <div class="show-address"><%= @business.address_number %> <%= @business.street_name %></div>
          <div class="show-address"><%= @business.city %>, <%= @business.state_abbrev %> <%= @business.zip_code %></div>
        </div>
        <div class="hours-title" style="font-size: 20px; font-weight: bold; margin-top: 10px;">Hours</div>
        <div class="show-hours" style="margin-left: 40px;">
          <div class="hours" style="margin-bottom: 10px;">
            <table>
              <tr>
                <td>Mon</td>
                <td><%= @business.monday %></td>
              </tr>
              <tr>
                <td>Tue</td>
                <td><%= @business.tuesday %></td>
              </tr>
              <tr>
                <td>Wed</td>
                <td><%= @business.wednesday %></td>
              </tr>
              <tr>
                <td>Thu</td>
                <td><%= @business.thursday %></td>
              </tr>
              <tr>
                <td>Fri</td>
                <td><%= @business.friday %></td>
              </tr>
              <tr>
                <td>Sat</td>
                <td><%= @business.saturday %></td>
              </tr>
              <tr>
                <td>Sun</td>
                <td><%= @business.sunday %></td>
              </tr>
            </table>
          </div>
        </div>
        <div id="map"></div>
      </div>
    </div>
    <br>
    <h2>Reviews</h2>
    <% @business_comments.each do |comment | %>
      <div class="comments"><%= comment.body %> - 
        <%= comment.user.firstname %>
          <% if @ratings.where(business_id: @business.id, user_id: comment.user.id).first %>
            <% @ratings.where(business_id: @business.id, user_id: comment.user.id).first.rating.times do |i| %>
              <img class="comment-paws" src="<%= asset_path('paw.png') %>"/>
            <% end %>
          <% end %>   
          <% if logged_in? && (comment.user_id == current_user.id) %>
            <%= link_to "edit", edit_business_comment_path(comment.id) %>     
          <% end %>
      </div>
    <% end %>
    <br>
    <div>
      <% if logged_in?  %>
        <% if flash[:messages] %>
          <h2 class="register-flash"><%= flash[:messages] %></h2>
        <% end %>
        <% if @business_comments.where(user_id: current_user.id, business_id: @business.id).first == nil %>
          <%= form_for :business_comment, url:"/business_comments" do |f| %>
            <%= f.text_field :body, placeholder: "comment", class: "comment-field" %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <%= f.hidden_field :business_id, value: @business.id %>
            <%= f.submit "Add Comment", class: "page-top-buttons" %>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <br>
    <br>
  </div>
</div>