config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/', controller: "businesses", action: "index"

  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  delete 'login', to: 'sessions#destroy'

  # resources :sessions

  resources :users
  
  resources :businesses

  resources :business_comments

  resources :business_user_relationships

  resources :user_user_relationships

  resources :user_check_ins

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true
  
end

app/models/business.rb
class Business < ApplicationRecord

  geocoded_by :address
  after_validation :geocode

  has_many :business_comments
  has_many :users, through: :business_comments
  has_many :ratings
  has_many :users, through: :ratings
  has_many :business_user_relationships
  has_many :users, through: :business_user_relationships
  has_many :user_check_ins
  has_many :users, through: :user_check_ins

  def average
    average = 0
    self.ratings.each do |rating|
      average = average + rating.rating
    end

    if self.ratings.length == 0
      return 0
    else
      average/self.ratings.length
    end
  end
  
end

app/models/business_comment.rb
class BusinessComment < ApplicationRecord

  validates :body, presence: true,
    length: { maximum: 100 , message: "over 100 characters"},
    format: { with: /\A[a-zA-Z0-9 !.,'?]+\z/i, message: "special characters are not allowed" }

  belongs_to :business
  belongs_to :user
  
end

app/models/business_user_relationship.rb
class BusinessUserRelationship < ApplicationRecord

  belongs_to :business
  belongs_to :user
  
end

app/models/rating.rb
class Rating < ApplicationRecord
    belongs_to :business
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
   
  has_secure_password

  validates :username, presence: true,
    length: { minimum: 2, maximum: 15 , message: "must be between 2-15 characters"}, 
    format: { with: /\A[a-zA-Z0-9_]+\z/i, message: "can only consist of letters, numbers and underscores" },
    uniqueness: true
  validates :firstname, presence: true,
    length: { minmum: 2, maximum: 15, message: "must be between 2-15 characters"},
    format: { with: /\A[a-zA-Z]+\z/i, message: "can only consist of letters"}
  validates :password, presence: true,
    length: { minimum: 6, maximum: 15, message: "must be between 6-15 characters"}

  has_many :business_comments
  has_many :businesses, through: :business_comments
  has_many :ratings
  has_many :businesses, through: :ratings
  has_many :business_user_relationships
  has_many :businesses, through: :business_user_relationships
  has_many :user_user_relationships
  has_many :users, through: :user_user_relationships
  has_many :user_check_ins
  has_many :businesses, through: :user_check_ins

  has_one_attached :avatar
  # has_may_attached

end

app/models/user_check_in.rb
class UserCheckIn < ApplicationRecord

  belongs_to :business
  belongs_to :user

end

app/models/user_user_relationship.rb
class UserUserRelationship < ApplicationRecord

  belongs_to :user

  def friend?(users, current_user)
    if (self.user_id == current_user.id) && (self.relationship == true)
      users.where(id: self.friend_user_id).first.firstname
    elsif (self.friend_user_id == current_user.id) && (self.relationship == true)
      users.where(id: self.user_id).first.firstname
    end
  end

  def friend_requests?(current_user)
    if (self.friend_user_id == current_user.id) && !(self.relationship == true)
      true
    end
  end

  # def friend_or_request?(user, current_user)
  #   if !(self == nil)
  #     if !(self.user_id == user.id && self.friend_user_id == current_user.id && self.relationship = true)
  #       if !(self.user_id == current_user.id && self.friend_user_id == user.id && self.relationship = true)
  #         if !(self.user_id == user.id && self.friend_user_id == current_user.id && self.relationship = false)
  #           if !(self.user_id == current_user.id && self.friend_user_id == user.id && self.relationship = false)
  #             true
  #           end
  #         end
  #       end
  #     end
  #   end
  # end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def current_user
    User.find_by(id: session[:user_id])
  end
  
  helper_method :current_user

  def logged_in?
    !current_user.nil?
  end
  helper_method :logged_in? 
   
end

app/controllers/business_comments_controller.rb
class BusinessCommentsController < ApplicationController

  def index
  end
    
  def new
    @business_comment = BusinessComment.new
  end

  def create
    @business_comment = BusinessComment.new(params.require(:business_comment).permit(:body, :user_id, :business_id))
    if @business_comment.valid?
      @business_comment.save

      redirect_to request.referrer
    else
      flash[:messages] = @business_comment.errors.full_messages[0]
     
      redirect_to request.referrer 
    end        
  end

  def edit
    @business_comment = BusinessComment.find(params[:id])
  end

  def update

  end

  def destroy
  end
  
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController

  def index
    @businesses = Business.all
  end

  def show
    @business = Business.where(id: params[:id]).first
    @business_comments = @business.business_comments
    @ratings = Rating.all
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    render plain: "Final Project"
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
    
      redirect_to '/'
    else

      redirect_to '/login'
    end
  end

  def destroy
    reset_session

    redirect_to '/'
  end
  
end

app/controllers/user_check_ins_controller.rb
class UserCheckInsController < ApplicationController

  def index
    @user_check_ins = UserCheckIn.all
  end
  
  def new
    @user_check_in = UserCheckIn.new 
  end
  
  def create
    @user_check_in = UserCheckIn.create(params.require(:user_check_in).permit(:checked_in, :business_id, :user_id))
  
    redirect_to request.referrer
  end
  
  def destroy
    @user_check_in = UserCheckIn.find(params[:id])
    @user_check_in.destroy
  
    redirect_to request.referrer
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
  def index
    @user_relationships = UserUserRelationship.all
    @user_check_ins = UserCheckIn.all

    @businesses = Business.all
    @users = User.all
  end

  def show
  end
  
  def new
    @user = User.new
  end

  def create
    # @user = User.create(params.require(:user).permit(:firstname, :username, :password))
    @user = User.new(params.require(:user).permit(:avatar, :firstname, :username, :password))
    if @user.valid?
      @user.save
      session[:user_id] = @user.id

      redirect_to '/users'
    else
      flash.now[:messages] = @user.errors.full_messages[0]

      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/business_comments_helper.rb
module BusinessCommentsHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_check_ins_helper.rb
module UserCheckInsHelper
end

app/helpers/user_user_relationships_helper.rb
module UserUserRelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
  <div class="future-navbar-items">
    <div class="greeting" style="width: 100%; background: gray; padding-bottom: 10px; padding-top: 10px; position:fixed;">
        <div style="margin-left: 10px; margin-top: auto; margin-bottom: auto; font-size: 30px; margin-right: 40px; color: white;">
                        <span style="border: 3px solid white; border-radius: 100%; padding: 5px; background-color: rgba(0, 0, 0, 0.5);">DF</span> 

            St. Pete</div>
        <div style="text-align: left;"><%= button_to "Home", '/businesses', method: :get, class: "top-buttons", style: "margin:0px; padding-top: 2px; padding-bottom: 2px;" %></div>
        <div><%= button_to "Profile", "/users/#{current_user.id}", method: :get, class: "top-buttons", style: "margin:0px; padding-top: 2px; padding-bottom: 2px;"%></div>

        <div><%= button_to "Logout", "/login", method: :delete, class: "top-buttons", style: "margin:0px; padding-top: 2px; padding-bottom: 2px;" %></div>
  </div>
</div>
<div class="body-container">
<% if logged_in? %>
    <h1 style="margin-top: 75px; margin-left: 100px;"><%=current_user.firstname.capitalize %>'s Dashboard</h1>
<% end %> 

<div class="business-card-container">
    <% @businesses.each do |business | %>
        <% if business.business_user_relationships.where(user_id: current_user.id).first %>
            <div class="business_card">
            <img class="bc_img" src="<%= business.img_url %>"/>
            <div class="bc_name" style="font-size: 20px; margin-bottom: 0px;"><%= business.name %></div>
                        <%# <p class="rating">Rating:</p>  %>
            <div style="display: flex; justify-content: center; margin-bottom: 8px;">
            <% if business.average  %>               
                <div class="paws" style="text-align: center">
                    <% business.average.times do |i| %>
                        <img class="paw" src="<%= asset_path('paw.png') %>"/>
                        <% end %>
                    <% (5 - business.average).times do |i| %>
                        <img class="paw" src="<%= asset_path('graypaw.png') %>"/>
                    <% end %>
                
                </div>

  
            <% end %>
            </div>
            <div class="bc_phone" style="margin-bottom: 5px;"><%= business.phone_number %></div>
            <div class="bc_address"><%= business.address_number %> <%= business.street_name %></div>
            <div style="display: flex; justify-content: center; margin-top: 50px;">
                <div><%= button_to "Remove", business_user_relationship_path(id: business.business_user_relationships.first.id), method: :delete, class: "top-buttons", style: "margin-left: auto; margin-right: auto; padding: 5px;"%></div>
               </div> 
                <br>
                <div>
                    <div>Checked in:   
                        <% if !(business.user_check_ins.first == nil) %>
                            <% business.user_check_ins.each do |check_in| %>
                                <% if check_in.user_id == current_user.id %>
                                    You
                                <% elsif %>
                                    <%= check_in.user.firstname %>
                                <% end %> 
                            <% end %>
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>
    <% end %>
</div>
</br>
<div style="margin-left: 100px;">
<h2>Other Users</h2>
<% @users.each do |user| %>
    <% if (user.id != current_user.id) %>
        <% if @user_relationships.where(user_id: user.id, friend_user_id: current_user.id, relationship: true).first == nil %>
            <% if @user_relationships.where(user_id: current_user.id, friend_user_id: user.id, relationship: true).first == nil%>
                <% if @user_relationships.where(user_id: user.id, friend_user_id: current_user.id, relationship: false).first == nil %>
                    <% if @user_relationships.where(user_id: current_user.id, friend_user_id: user.id, relationship: false).first == nil%>
                        <div  style="display: flex">
                            <div><%= user.firstname %>  </div>
                            <%= form_for :user_user_relationship, url:"/user_user_relationships" do |f| %>
                                <%= f.hidden_field :user_id, value: current_user.id %>
                                <%= f.hidden_field :friend_user_id, value: user.id %>
                                <div style="margin-left: 20px; margin-bottom: 8px;"><%= f.submit "Send friend request", class: "page-top-buttons" %></div>
                            <% end %>
                        </div>
                    <% end %>
                <% end %>
            <% end %>  
        <% end %>
    <% end %>
<% end %>

<h2>Friends</h2>
<% @user_relationships.each do |user_relationship| %>
    <div><%= user_relationship.friend?(@users, current_user) %></div>
<% end %>

<h2>Friend Requests</h2>
<% @user_relationships.each do |user_relationship|%>
    <% if user_relationship.friend_requests?(current_user) %>
        <p>You have a friend request from <%= @users.where(id: user_relationship.user_id).first.firstname %></p>
        <%= form_for :user_user_relationship, url:"/user_user_relationships/#{user_relationship.id}", method: :put do |f| %>
            <%= f.hidden_field :relationship, value: true %>
            <%= f.submit "Accept" %>
        <% end %>
    <% end %>
<% end %>   

<%# <h2>Your Pending Friend Requests</h2>
<p>todo</p> %>
</div>
</div>

app/views/users/login.html.erb
  <div class="future-navbar-items">
    <div class="greeting" style="width: 100%; background: gray; padding-bottom: 10px; padding-top: 10px; position:fixed;">
        <div style="margin-left: 10px; margin-top: auto; margin-bottom: auto; font-size: 30px; margin-right: 40px; color: white;">
            <span style="border: 3px solid white; border-radius: 100%; padding: 5px; background-color: rgba(0, 0, 0, 0.5);">DF</span> 
            St. Pete</div>
        <div style="text-align: left;"><%= button_to "Home", '/businesses', method: :get, class: "top-buttons", style: "margin:0px; padding-top: 2px; padding-bottom: 2px;" %></div>
  

        <div><%= button_to "Dashboard", '/users', method: :get, class: "top-buttons", style: "margin:0px; padding-top: 2px; padding-bottom: 2px;" %></div>
        <div><%= button_to "Logout", "/login", method: :delete, class: "top-buttons", style: "margin:0px; padding-top: 2px; padding-bottom: 2px;" %></div>
  </div>
</div>

<h1>hello</h1>

<%= form_tag '/users/login' do %>
<%= label_tag :username %>
<%= text_field_tag :username %>
<%= label_tag :password %>
<%= passwordtext_field_tag :password %>
<%= submit_tag "Login" %>
<% end %>

app/views/users/new.html.erb
  <div class="future-navbar-items">
    <div class="greeting" style="width: 100%; background: gray; padding-bottom: 10px; padding-top: 10px; position:fixed;">
        <div style="margin-left: 10px; margin-top: auto; margin-bottom: auto; font-size: 30px; margin-right: 40px; color: white;">
            <span style="border: 3px solid white; border-radius: 100%; padding: 5px; background-color: rgba(0, 0, 0, 0.5);">DF</span> 
            St. Pete</div>
        <div style="text-align: left;"><%= button_to "Home", '/businesses', method: :get, class: "top-buttons", style: "margin:0px; padding-top: 2px; padding-bottom: 2px;" %></div>
  
        <div><%= button_to "Login", "/login", method: :get, class: "top-buttons", style: "margin:0px; padding-top: 2px; padding-bottom: 2px;"  %></div>
  </div>
</div>
<div class=registration-container style="margin-left: 100px;">
<h1 style="margin-top: 100px;">Create a New Account</h1>
 <% if flash[:messages] %>
   <h2 class="register-flash"><%= flash[:messages] %></h2>
<% end %>
<%= form_for @user do |f| %>
    <%= f.label "Profile Photo" %>
    <%= f.file_field :avatar%>
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %><br>
    <%= f.label :username %><br>
    <%= f.text_field :username %><br>
    <%= f.label :password %><br>
    <%= f.password_field :password %><br><br>
    <%= f.submit %>
<% end %>
</div>

app/views/users/show.html.erb
  <div class="future-navbar-items">
    <div class="greeting" style="width: 100%; background: gray; padding-bottom: 10px; padding-top: 10px; position:fixed;">
        <div style="margin-left: 10px; margin-top: auto; margin-bottom: auto; font-size: 30px; margin-right: 40px; color: white;">
            <span style="border: 3px solid white; border-radius: 100%; padding: 5px; background-color: rgba(0, 0, 0, 0.5);">DF</span> 
            St. Pete</div>
        <div style="text-align: left;"><%= button_to "Home", '/businesses', method: :get, class: "top-buttons", style: "margin:0px; padding-top: 2px; padding-bottom: 2px;" %></div>
  

        <div><%= button_to "Dashboard", '/users', method: :get, class: "top-buttons", style: "margin:0px; padding-top: 2px; padding-bottom: 2px;" %></div>
        <div><%= button_to "Logout", "/login", method: :delete, class: "top-buttons", style: "margin:0px; padding-top: 2px; padding-bottom: 2px;" %></div>
  </div>
</div>

<h1 class="pp-name" style="margin-top: 100px"><%= current_user.firstname %>'s Profile Page</h1>

<% if current_user.avatar.attached? %>
    <%= image_tag current_user.avatar, class: "profile-pic"%>
<% else%>
    <%= image_tag asset_path('sasha.png'), class: "profile-pic" %>
<%end%>

<h2 class="pp-name">Not sure what content this page will hold yet</h2>
<div class="gibberish">Doggo ipsum bork heck ur givin me a spook boofers boof, ur givin me a spook stop it fren you are doing me the shock, pats the neighborhood pupper doggorino. Sub woofer dat tungg tho super chub, heckin good boys. You are doing me a frighten I am bekom fat wow such tempt he made many woofs, blep stop it fren. Many pats ruff borkf, clouds. Snoot stop it fren doggo blop length boy very hand that feed shibe, pupperino very jealous pupper doing me a frighten. Boof blep corgo mlem, tungg very good spot. Blop heckin good boys and girls big ol pupper borkf doggorino aqua doggo much ruin diet, borking doggo tungg heckin adorable doggo.   Adorable doggo borkdrive you are doing me the shock heckin angery woofer lotsa pats, you are doin me a concern lotsa pats wrinkler. Very jealous pupper very hand that feed shibe borkf super chub smol, you are doin me a concern much ruin diet clouds, dat tungg tho smol noodle horse.

Bork ur givin me a spook adorable doggo fluffer vvv, you are doing me the shock many pats shoob length boy long woofer, smol pats smol. Doggorino floofs pupperino wow very biscit ur givin me a spook long bois, bork maximum borkdrive boofers. Very jealous pupper the neighborhood pupper ruff clouds doggo clouds, waggy wags you are doing me a frighten blop many pats. Borkf you are doing me a frighten puggorino yapper heckin angery woofer adorable doggo floofs big ol, mlem yapper ruff stop it fren doggorino. The neighborhood pupper maximum borkdrive heckin good boys wow very biscit smol length boy noodle horse, much ruin diet many pats what a nice floof wow very biscit tungg.

Smol stop it fren he made many woofs many pats fluffer, floofs lotsa pats adorable doggo, blop yapper tungg. woofer. Very good spot long water shoob noodle horse he made many woofs pupper much ruin diet, long bois boof doge. Fat boi corgo you are doin me a concern h*ck much ruin diet you are doing me a frighten, heckin wow such tempt woofer borkdrive. Doge fluffer boofers long doggo long woofer, pupperino pats long woofer, borkf heckin good boys puggorino. Doggo mlem very hand that feed shibe pupperino ur givin me a spook, very jealous pupper wow very biscit. Smol smol borking doggo with a long snoot for pats many pats shibe heck very jealous pupper, tungg pupper pupperino. Lotsa pats ur givin me a spook shooberino puggorino smol borking doggo with a long snoot for pats doing me a frighten heckin borkdrive, long water shoob blop noodle horse big ol pupper doggo noodle horse. Borkdrive maximum borkdrive big ol wrinkler boofers heckin angery woofer, stop it fren big ol clouds maximum borkdrive.   </div>